spring.application.name=airBnb-App

spring.datasource.url=jdbc:postgresql://localhost:5432/AirBnbApp
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

server.servlet.context-path=/api/v1

jwt.secretKey=dhs8979dfhdsiyfd6f78dsfydshf87fds87f5srdtgdf8d7s7suhd898767ds7s8